_target_: src.models.pluto_rl.stage1_warmup_trainer.ProbabilisticWarmupTrainer

lambda_nll: 0.1
lambda_nll_end: 1.0
lambda_nll_ramp_ratio: 0.3
freeze_log_std_z_epochs: 1
use_collision_loss: true
use_contrast_loss: true
regulate_yaw: false
